id: P010618
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 2021-12-20 10:16:44.996461
source_metadata:
  id: bdr:W1GS53494
  title: དགོན་གོང་མའི་ལོ་རྒྱུས་འཕོ་འགྱུར་རང་ཡུལ་སྲོལ
  author: ''
  volumes:
    70ddeb1cbc0847bcbd7d027f81c0c3b8:
      image_group_id: I1GS53496
      title: ''
      volume_number: 1
      total_pages: 295
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
